version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: incode-db1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: incode
    ports:
      - "5432:5432"

  service-app:
    build: .
    container_name: simple-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/incode
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "9876:9876"